MLH-Fellowship/gitcord-bot

- .gitignore
- LICENSE
- README.md
- main.js
- package-lock.json
- package.json
Fix unrelated histories issue from template unrelated main and staging branches due to discord-bot branch being created from main.
Also contains work for discord-bot branch. @dtemir's initial Discord bot creation and my own improvements - see commit history.
> Fix Unrelated Histories and Initial Discord Bot Creation

- commands/github.js
- commands/testing.js
- main.js
Through this PR I have tried to refactor the code and shift the commands from `main.js` to files under `commands` folder.
> Refactored code to create separate file for commands

- github.js
- main.js
- package-lock.json
- package.json
Have added the GitHub API integration using Octonode JS wrapper.
Auth works using personal GitHub token. @Inoxia25 is looking into how we can prompt users to create and enter one to use with our Discord bot.
Have added a method to get all PRs (to test auth) and can post comments on an issue (part of MVP functionality). 
Content is hardcoded so next steps are to extract that into variables, an array or a class and modify the `getPullRequests()` function to post comments on PRs.
> Added GitHub API Integration

- commands/github.js
- main.js
Currently a test (draft PR) to test using the bot to post a comment on a PR
> GitHub PR Commenting

- commands/github.js
- commands/testing.js
- main.js
`-github` tells you to enter your github personal token.
Example for the next command to authenticate github with the bot
`-github-info 6875765768bugjbjjn` 
`github-post` to post your comment on the issue. (Currently not working, having authentication issues)
> Get tokens from the user

- commands/help.js
- main.js
A help comment is added which performs the following functionality:
`-help` : Gives a list of all the bot commands available.
`-help [command name]` : Gives the description of the specific command.
- Add the commands dynamically to the help command, so that whenever new commands are added to the bot, `-help` is automatically updated. Currently, the commands and their descriptions are hardcoded in `help.js` file.
> Added help command

- commands/github.js
- main.js
- package-lock.json
- package.json
- The bot now replies to messages posted by users which reduces the number of commands needed.
- The code has also gone through a big refactor so the commands folder is properly linked to main.js using the methods outlined in [Discord.js docs](https://discordjs.guide/command-handling/#individual-command-files)
- Commands in the commands folder are now automatically linked and we can access the message object rather than having to use botMessage.call and create a new function.
**To Fix:**
-The `-github-info` command reply isn't working but think that may be due to conflicting bot instances running.
> Code Refactor & Bot Replies

- commands/help.js
- main.js
Help.js now dynamically links to main.js similar to #11. In the same vein, this.channel.send has been refactored to message.reply.
**TODO:** Implement dynamic help commands instead of hardcoded with @Inoxia25 is working on in her branch.
> Refactored Help.js to Link Dynamically 

- commands/help.js
- main.js
Reverts MLH-Fellowship/pod-3.1.3-team-4#14
> Revert "Refactored Help.js to Link Dynamically "

- commands/github.js
Test merging of @Inoxia25's working branch with a clone of staging.
> Test Merge of Staging Clone

- .github/workflows/project-assign.yml
- main.js
Added a GitHub [action](https://github.com/srggrs/assign-one-project-github-action) to auto assign issues and PRs to the GitCord Project board.
Auto adds new issues and PRs to GitHub Projects so we don't need to remember to manually do this. Allows us to easily manage the stage of our project, who's been assigned what issue and the current status of reviews and PRs.
Added a `project-assign.yml` file in the new `.github/workflows` folder.
> Implements Auto Assignment for GitHub Projects

- commands/help.js
- main.js
Made the `help.js` command dynamic, so instead of hardcoding the names of the commands and their descriptions, the command fetches it dynamically from `commands/` folder.
- `help.js` was changed to make the help command dynamic.
-  `main.js`  was changed
> Added dynamic help command

- pull_request_template.md
Added a pull request template which requires merging into main to take affect.
See #29 for details.
> Added a Pull Request Template

- commands/github-info.js
- commands/github-post-comment.js
- commands/github-post-standup.js
- commands/github-projects.js
- commands/github-update-standup.js
- commands/github.info.js
- commands/tech-stack.js
This PR adds value by allowing users to manage and create GitHub projects via our GitCord Bot instead of having to use the GitHub UI
- Added `github-projects.js` - to house all GitHub Projects code
- Added `github-projects` command - to choose between selecting and creating a project
- Added `github-projects create-project` command - to create a project
- Added `github-projects select-project` command - to select a project - lists all columns (lists)
- Added `github-projects create-column` command - to create new columns (lists)
- Added `github-projects select-column` command - to retrieve card info from columns
- **Storing Data** - Be able to store information such as projectID, cardID and columnID so they can be reused for future queries
- **Project Name** - Show users the project name …
> Added GitHub Projects Functionality

- README.md
Updated and formatted readme to provide a clear structure to fill out and will inform readers of what our project is about.
- Added sections
- Added badges
- Added header image
- Added unicode symbols to main headings
- Added table of contents for main headings
- **Fill Out Readme Sections** - Continue filling out readme sections next week.
This closes #31.
> Updated and Formatted Readme

- commands/github-info.js
- commands/github-post-comment.js
- commands/github-post-standup.js
- commands/github-projects.js
- commands/github-update-standup.js
- commands/help.js
- commands/lighthouse.js
- commands/tech-stack.js
- main.js
A usage section in the help commands would give the user a better understanding of how to use GitCord and use all its commands.
- Added `usage` instructions in all files under `/commands` folder.
- Refactored `help.js` to use template literals according to best practices
An example of the usage section:
NA
This closes #56
> Added usage section to help commands.

- commands/github-info.js
- commands/github-post-comment.js
- commands/github-post-standup.js
- commands/github-projects.js
- commands/github-update-standup.js
- database.js
- github.js
To improve code readability and DRY, I've refactored the DB code so it uses the `database.js` file and the db is now used for all GitHub token storage and retrieval.
- Adds `database.js` file - stores database config and GitHub write/read Token functions as well as `fetchGit()`
- A `db.fetchGit(discordID).then function to retrieve GitHub Token, set octokit variable and then call relevant GitHub API functions`
N/A - Code Change
- **Set GitHub Token variable in `database.js`** - Be able to set the `octokit` variable in `database.js` so it can be reused in all GitHub API files so the `db.fetchGit()` function can be removed. Current blocker is that since it uses new, (`let octokit = new MyOctokit({ auth: result });`), it doesn't seem to work. Perhaps ask Robbie?
Closes #26.
> Refactored DB Code to use database.js

- site/home.css
- site/home.html
Improves styling of the site
- Added cards using flexbox bootstrap in `home.css`.
The background should be dark blue, looks pink coz of the animation.
- Add Commands Section and logo
This closes #66
> Added cards to Website

- site/home.css
- site/home.html
Improves the readability of `/site/home.css` file.
-Changed the class name and animation name in `/site/home.css`
- Changed the title in `/site/home.html`.
NA
This closes #59
> Refactored CSS Code

- commands/github-info.js
- github-token.txt
- main.js
Added a check to make sure the GitHub token entered is valid. This is vital because without it GitHub request would fail.
- Adds `octokit.rest.users.getAuthenticated()` to `github-info.js` to check if token is valid before calling db insert or update functions
- **Remove `console.logs`** - Removed uneeded console.logs in `github-info.js`
This closes #54.
> Added Check for GitHub Token Validity

- package-lock.json
- package.json
Adds `nodemon` package so the server is automatically reloaded whenever a change to a `.js` file occurs.
- Adds `nodemon` package to `package.json` as a `devDependency`
-  Adds `nodemonConfig` to `package.json` to set `nodemon` to only watch `.js` files
- Adds a `watch` command as a `npm` script to run `nodemon`
- Alters the `npm start` script to add the `watch` script to `npm start`
This closes #75.
> Adds Hot Reloading

- README.md
Updated Readme with new website URL
> Updated Website URL
